version: '3.9'
services: 
  db:
    image: postgres:latest
    env_file: 
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  pg_data: